import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hinting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Latest Blogs</h1>
        <div className={styles.grid}>
          <Link href="/blogpost/Documentation">
            <div className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </Link>

          <Link href="/blogpost/Deploy">
            <div className={styles.card}>
              <h2>Deploy &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </Link>

          <Link href="/blogpost/Example">
            <div className={styles.card}>
              <h2>Example &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </Link>

          <Link href="/blogpost/Learn">
            <div className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
