import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hinting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
				<nav style={{display:"flex", alignItems:'center', justifyContent:'center', flexDirection: 'column'}}>
	        <h1 className={styles.title}>
	          Hunting Coders
	        </h1>
					<ul style={{display:"flex", alignItems:'center', justifyContent:'center'}}>
						<li className={styles.lists}>Home</li>
						<li className={styles.lists}>About</li>
						<li className={styles.lists}>Contact</li>
					</ul>
				</nav>

        <p className={styles.description}>
          Blog for coders by a Coder
        </p>

				<h1>PopularBlogs</h1>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://docs.replit.com/category/hosting"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              This website automatically deployed on Replit by hitting the run button!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built on
          <span className={styles.logo}>
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
          Replit
        </a>
      </footer>
    </div>
  )
}

export default Home
